import type { Collection, NewsArticle, Product } from "@/types/commerce";

const pkr = (amount: number) => ({ amount, currencyCode: "PKR" as const });

function img(seed: string, alt: string) {
  return {
    url: `https://images.unsplash.com/${seed}?auto=format&fit=crop&w=800&q=80`,
    alt,
    width: 800,
    height: 800,
  };
}

/** Demo catalog — replaced by Shopify when COMMERCE_PROVIDER=shopify */
export const DEMO_COLLECTIONS: Collection[] = [
  {
    id: "col-playstation",
    handle: "playstation",
    title: "PlayStation",
    description:
      "PS5 and PS4 consoles, exclusive games, DualSense controllers, VR, and official accessories.",
    image: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=1200&q=80",
    children: [
      "ps5-consoles",
      "ps5-games",
      "ps5-controllers",
      "ps5-accessories",
      "ps4-consoles",
      "ps4-games",
      "playstation-vr",
      "playstation-headsets",
    ],
    seoTitle: "PlayStation Consoles, Games & Accessories | ToyCompany",
    seoDescription:
      "Shop PlayStation 5, PS4, DualSense controllers, PSVR, headsets, and exclusive games at ToyCompany.",
  },
  {
    id: "col-xbox",
    handle: "xbox",
    title: "Xbox",
    description:
      "Xbox Series X|S, Xbox One, Game Pass-ready titles, Elite controllers, and Xbox accessories.",
    image: "https://images.unsplash.com/photo-1621259182978-fbf93132d53d?auto=format&fit=crop&w=1200&q=80",
    children: [
      "xbox-series-x",
      "xbox-series-s",
      "xbox-one",
      "xbox-360",
      "xbox-games",
      "xbox-controllers",
      "xbox-accessories",
      "xbox-headsets",
    ],
    seoTitle: "Xbox Consoles, Games & Accessories | ToyCompany",
    seoDescription:
      "Buy Xbox Series X, Series S, controllers, headsets, and the latest Xbox games online.",
  },
  {
    id: "col-nintendo",
    handle: "nintendo",
    title: "Nintendo",
    description:
      "Nintendo Switch and OLED systems, Joy-Cons, first-party games, and Switch accessories.",
    image: "https://images.unsplash.com/photo-1578303517154-48091adcdb15?auto=format&fit=crop&w=1200&q=80",
    children: [
      "nintendo-switch",
      "nintendo-switch-oled",
      "nintendo-switch-games",
      "nintendo-switch-controllers",
      "nintendo-switch-accessories",
    ],
    seoTitle: "Nintendo Switch Consoles & Games | ToyCompany",
    seoDescription:
      "Shop Nintendo Switch, OLED, Joy-Cons, and exclusive Nintendo games at ToyCompany.",
  },
  {
    id: "col-games",
    handle: "games",
    title: "Video Games",
    description:
      "New releases, best sellers, used titles, and games for every major platform.",
    image: "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?auto=format&fit=crop&w=1200&q=80",
    children: [
      "new-releases",
      "best-sellers",
      "pre-owned-games",
      "ps5-games",
      "ps4-games",
      "xbox-games",
      "nintendo-games",
      "pc-games",
    ],
    seoTitle: "Buy Video Games Online | ToyCompany",
    seoDescription:
      "Browse new releases, best sellers, and used games for PS5, Xbox, Nintendo, and PC.",
  },
  {
    id: "col-accessories",
    handle: "accessories",
    title: "Gaming Accessories",
    description:
      "Controllers, headsets, keyboards, mice, chairs, wheels, microphones, and more.",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80",
    children: [
      "gaming-controllers",
      "gaming-headsets",
      "gaming-keyboards",
      "gaming-mice",
      "gaming-mouse-pads",
      "gaming-chairs",
      "gaming-wheels",
      "gaming-microphones",
      "hdmi-cables",
      "charging-stations",
      "console-stands",
      "storage-devices",
    ],
    seoTitle: "Gaming Accessories Store | ToyCompany",
    seoDescription:
      "Upgrade your setup with gaming headsets, keyboards, mice, chairs, and console accessories.",
  },
  {
    id: "col-consoles",
    handle: "consoles",
    title: "Consoles",
    description: "Latest and previous-gen gaming consoles from Sony, Microsoft, and Nintendo.",
    image: "https://images.unsplash.com/photo-1486401899868-0e435ed85128?auto=format&fit=crop&w=1200&q=80",
    children: ["ps5-consoles", "ps4-consoles", "xbox-series-x", "xbox-series-s", "xbox-one", "xbox-360", "nintendo-switch", "nintendo-switch-oled"],
    seoTitle: "Gaming Consoles for Sale | ToyCompany",
    seoDescription: "Shop PS5, Xbox Series X|S, and Nintendo Switch consoles with fast delivery.",
  },
  {
    id: "col-gift-cards",
    handle: "gift-cards",
    title: "Gift Cards & Digital Codes",
    description:
      "PlayStation Network, Steam USD, Nintendo eShop, Roblox, and Fortnite V-Bucks digital gift cards — instant WhatsApp delivery.",
    image: "/gift-cards/steam.svg",
    children: ["digital-codes"],
    seoTitle: "Gift Cards & Digital Codes | ToyCompany",
    seoDescription:
      "Buy PSN, Steam, Nintendo eShop, Roblox, and Fortnite V-Bucks gift cards online in Pakistan.",
  },
  {
    id: "col-deals",
    handle: "deals",
    title: "Deals",
    description: "Limited-time discounts on consoles, games, and accessories.",
    seoTitle: "Gaming Deals & Discounts | ToyCompany",
    seoDescription: "Save on gaming gear with ToyCompany special deals and flash sales.",
  },
  {
    id: "col-new-arrivals",
    handle: "new-arrivals",
    title: "New Arrivals",
    description: "Fresh drops — recently added consoles, games, and gear.",
    seoTitle: "New Gaming Arrivals | ToyCompany",
    seoDescription: "Discover the newest games and accessories just added to ToyCompany.",
  },
  // Subcollections
  ...[
    ["ps5-consoles", "PS5 Consoles", "playstation"],
    ["ps5-games", "PS5 Games", "playstation"],
    ["ps5-controllers", "PS5 Controllers", "playstation"],
    ["ps5-accessories", "PS5 Accessories", "playstation"],
    ["ps4-consoles", "PS4 Consoles", "playstation"],
    ["ps4-games", "PS4 Games", "playstation"],
    ["playstation-vr", "PlayStation VR", "playstation"],
    ["playstation-headsets", "PlayStation Headsets", "playstation"],
    ["xbox-series-x", "Xbox Series X", "xbox"],
    ["xbox-series-s", "Xbox Series S", "xbox"],
    ["xbox-one", "Xbox One", "xbox"],
    ["xbox-360", "Xbox 360", "xbox"],
    ["xbox-games", "Xbox Games", "xbox"],
    ["xbox-controllers", "Xbox Controllers", "xbox"],
    ["xbox-accessories", "Xbox Accessories", "xbox"],
    ["xbox-headsets", "Xbox Headsets", "xbox"],
    ["nintendo-switch", "Nintendo Switch", "nintendo"],
    ["nintendo-switch-oled", "Nintendo Switch OLED", "nintendo"],
    ["nintendo-switch-games", "Nintendo Switch Games", "nintendo"],
    ["nintendo-switch-controllers", "Nintendo Switch Controllers", "nintendo"],
    ["nintendo-switch-accessories", "Nintendo Switch Accessories", "nintendo"],
    ["gaming-controllers", "Gaming Controllers", "accessories"],
    ["gaming-headsets", "Gaming Headsets", "accessories"],
    ["gaming-keyboards", "Gaming Keyboards", "accessories"],
    ["gaming-mice", "Gaming Mice", "accessories"],
    ["gaming-mouse-pads", "Gaming Mouse Pads", "accessories"],
    ["gaming-chairs", "Gaming Chairs", "accessories"],
    ["gaming-wheels", "Gaming Wheels", "accessories"],
    ["gaming-microphones", "Gaming Microphones", "accessories"],
    ["hdmi-cables", "HDMI Cables", "accessories"],
    ["charging-stations", "Charging Stations", "accessories"],
    ["console-stands", "Console Stands", "accessories"],
    ["storage-devices", "Storage Devices", "accessories"],
    ["new-releases", "New Releases", "games"],
    ["best-sellers", "Best Sellers", "games"],
    ["pre-owned-games", "Used Games", "games"],
    ["pc-games", "PC Games", "games"],
    ["digital-codes", "Digital Codes", "gift-cards"],
  ].map(([handle, title, parent], i) => ({
    id: `col-sub-${i}`,
    handle,
    title,
    description:
      handle === "pre-owned-games"
        ? "Browse all used / pre-owned game discs for PS5, PS4, Xbox, and Nintendo Switch — tested stock at ToyCompany."
        : `Shop ${title} at ToyCompany — authentic products, fast shipping across Pakistan.`,
    parentHandle: parent,
    seoTitle:
      handle === "pre-owned-games"
        ? "Used Games (Pre-Owned Discs) | ToyCompany"
        : `${title} | ToyCompany`,
    seoDescription:
      handle === "pre-owned-games"
        ? "Buy used PS5, PS4, Xbox, and Switch game discs in Pakistan. Certified pre-owned stock with fast delivery."
        : `Browse ${title} with competitive prices and trusted delivery.`,
  })),
];

export const DEMO_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    handle: "pulse-ps5-slim-disc",
    title: "PS5 Slim Disc Edition 1TB",
    brand: "Sony",
    description:
      "PS5 Slim Disc Edition with powerful gaming in a sleek compact design, 1TB SSD storage, Ultra HD Blu-ray disc drive, and DualSense wireless controller. Box includes console (CFI-2116 slim), DualSense controller, HDMI cable, AC power cord, USB cable, horizontal stand feet, and ASTRO’s PLAYROOM (pre-installed). Vertical stand sold separately.",
    category: "ps5-consoles",
    categoryPath: ["playstation", "ps5-consoles", "consoles"],
    platform: ["PlayStation 5"],
    tags: ["console", "ps5", "featured", "consoles"],
    condition: "new",
    rating: 4.9,
    reviewCount: 428,
    images: [
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/PS5-SLIM-2-1.jpg?v=1707360097",
        alt: "PS5 Slim Disc Edition 1TB",
        width: 1000,
        height: 1000,
      },
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/PS5-SLIM-2.jpg?v=1745507798",
        alt: "PS5 Slim Disc Edition 1TB side view",
        width: 1500,
        height: 1000,
      },
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/atp-ps5-slim-disc-edition-console-bundle-desktop-3-Format-976.png?v=1745507798",
        alt: "PS5 Slim Disc Edition 1TB bundle",
        width: 976,
        height: 976,
      },
    ],
    variants: [
      {
        id: "var-1",
        title: "Default",
        sku: "PTPK-PS5-SLIM-DISC-1TB",
        price: pkr(245000),
        compareAtPrice: pkr(275000),
        available: true,
        quantityAvailable: 8,
      },
    ],
    specs: [
      { label: "Storage", value: "1TB SSD" },
      { label: "Resolution", value: "Up to 4K" },
      { label: "Disc Drive", value: "Ultra HD Blu-ray" },
      { label: "Model", value: "CFI-2116 (Slim)" },
      { label: "HDR", value: "Yes" },
    ],
    compatibility: ["PlayStation 5", "PlayStation 5 Slim"],
    featured: true,
    bestSeller: true,
    newArrival: true,
    onDeal: true,
    dealEndsAt: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(),
    shippingInfo: "Free shipping on orders over Rs. 15,000. Dispatch within 24 hours.",
    createdAt: "2026-07-01T10:00:00Z",
  },
  {
    id: "prod-ps5-pro-digital-2tb",
    handle: "ps5-pro-digital-edition-2tb",
    title: "PS5 Pro Digital Edition 2TB",
    brand: "Sony",
    description:
      "PlayStation 5 Pro Digital Edition with PlayStation Spectral Super Resolution (PSSR) for ultra-sharp 4K, optimized high frame rates (60Hz / 120Hz), advanced ray tracing, and 2TB SSD storage. Includes DualSense wireless controller, HDMI cable, AC power cord, USB cable, horizontal stand feet, and ASTRO’s PLAYROOM (pre-installed). Disc drive and vertical stand sold separately.",
    category: "ps5-consoles",
    categoryPath: ["playstation", "ps5-consoles", "consoles"],
    platform: ["PlayStation 5"],
    tags: ["console", "ps5", "ps5-pro", "featured", "consoles"],
    condition: "new",
    rating: 4.9,
    reviewCount: 186,
    images: [
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/files/66BC9B74-4916-4250-9BF2-192F17F19EAA.jpg?v=1732613913",
        alt: "PS5 Pro Digital Edition 2TB",
        width: 1200,
        height: 1200,
      },
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/files/80699FD6-59A8-4411-B4E7-8091353E0634.jpg?v=1745507863",
        alt: "PS5 Pro Digital Edition 2TB front view",
        width: 1200,
        height: 1200,
      },
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/files/99A4B65E-EF0B-4A01-AEBD-53C380643BBA.jpg?v=1745507863",
        alt: "PS5 Pro Digital Edition 2TB with DualSense",
        width: 1200,
        height: 1200,
      },
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/files/68B43C02-AF4A-4B6A-9D1D-1A6608DF3E40.jpg?v=1745507863",
        alt: "PS5 Pro Digital Edition 2TB side view",
        width: 1200,
        height: 1200,
      },
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/files/IMG-9556.jpg?v=1745507863",
        alt: "PS5 Pro Digital Edition 2TB detail",
        width: 1200,
        height: 1200,
      },
    ],
    variants: [
      {
        id: "var-ps5-pro-digital-2tb",
        title: "Default",
        sku: "PTPK-PS5-PRO-DIGITAL-2TB",
        price: pkr(385000),
        available: true,
        quantityAvailable: 5,
      },
    ],
    specs: [
      { label: "Storage", value: "2TB SSD" },
      { label: "Resolution", value: "Up to 4K (PSSR)" },
      { label: "Frame Rate", value: "Up to 120 FPS" },
      { label: "Ray Tracing", value: "Advanced" },
      { label: "Edition", value: "Digital (no disc drive)" },
    ],
    compatibility: ["PlayStation 5", "PlayStation 5 Pro"],
    featured: true,
    bestSeller: true,
    newArrival: true,
    onDeal: false,
    shippingInfo: "Free shipping on orders over Rs. 15,000. Dispatch within 24 hours.",
    createdAt: "2026-07-26T12:00:00Z",
  },
  {
    id: "prod-ps5-spiderman-2-bundle",
    handle: "playstation-5-console-marvels-spiderman-2-limited-edition-bundle",
    title: "PlayStation 5 Console Marvel’s Spider-Man 2 Limited Edition Bundle",
    brand: "Sony",
    description:
      "PlayStation 5 Console – Marvel’s Spider-Man 2 Limited Edition Bundle with a symbiote takeover design. Includes PS5 console with Limited Edition console covers, Limited Edition DualSense wireless controller, and a voucher for a digital copy of Marvel’s Spider-Man 2. Play as Peter Parker and Miles Morales, swing across Marvel’s New York with Web Wings, and face Venom and the symbiote threat. Account for PlayStation Network and internet connection required to redeem voucher.",
    category: "ps5-consoles",
    categoryPath: ["playstation", "ps5-consoles", "consoles"],
    platform: ["PlayStation 5"],
    tags: ["console", "ps5", "bundle", "limited-edition", "featured", "consoles"],
    condition: "new",
    rating: 4.8,
    reviewCount: 142,
    images: [
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/SPIDERMAN-2-PS5.jpg?v=1707358678",
        alt: "PS5 Marvel’s Spider-Man 2 Limited Edition Bundle",
        width: 1200,
        height: 1200,
      },
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/SPIDERMAN-2-PS5-1.jpg?v=1707358678",
        alt: "PS5 Spider-Man 2 Limited Edition console",
        width: 1200,
        height: 1200,
      },
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/SPIDERMAN-2-PS5-2.jpg?v=1707358678",
        alt: "PS5 Spider-Man 2 Limited Edition DualSense",
        width: 1200,
        height: 1200,
      },
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/SPIDERMAN-2-PS5-3.jpg?v=1707358678",
        alt: "PS5 Spider-Man 2 Limited Edition covers",
        width: 1200,
        height: 1200,
      },
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/SPIDERMAN-2-PS5-4.jpg?v=1707358678",
        alt: "PS5 Spider-Man 2 Limited Edition bundle detail",
        width: 1200,
        height: 1200,
      },
    ],
    variants: [
      {
        id: "var-ps5-spiderman-2-bundle",
        title: "Default",
        sku: "PTPK-PS5-SM2-LE-BUNDLE",
        price: pkr(265000),
        available: true,
        quantityAvailable: 4,
      },
    ],
    specs: [
      { label: "Edition", value: "Marvel’s Spider-Man 2 Limited Edition" },
      { label: "Includes", value: "Console covers + DualSense + game voucher" },
      { label: "Storage", value: "Built-in SSD" },
      { label: "Platform", value: "PlayStation 5" },
    ],
    compatibility: ["PlayStation 5"],
    featured: true,
    bestSeller: false,
    newArrival: true,
    onDeal: false,
    shippingInfo: "Free shipping on orders over Rs. 15,000. Dispatch within 24 hours.",
    createdAt: "2026-07-26T12:30:00Z",
  },
  {
    id: "prod-ps4-pro-1tb",
    handle: "ps4-pro-1tb-4k-hdr",
    title: "Sony PlayStation 4 Pro 1TB Standard Official (Non-jailbreak) 4K HDR",
    brand: "Sony",
    description:
      "Feel the power of Pro — PlayStation 4 Pro 1TB with 4K-TV gaming and entertainment, faster frame rates in PS4 Pro enhanced titles, and richer colours with HDR. Play the latest PS4 blockbusters and exclusives in stunning 4K on a compatible TV, stream entertainment from 4K-ready services, and enjoy enhanced graphics and smoother performance. Official non-jailbreak console.",
    category: "ps4-consoles",
    categoryPath: ["playstation", "ps4-consoles", "consoles"],
    platform: ["PlayStation 4"],
    tags: ["console", "ps4", "ps4-pro", "featured", "consoles"],
    condition: "refurbished",
    rating: 4.6,
    reviewCount: 98,
    images: [
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/1-copy_3c691eed-b887-42ce-a0b0-82cc4a170c8e.jpg?v=1707365986",
        alt: "Sony PlayStation 4 Pro 1TB 4K HDR",
        width: 1200,
        height: 1200,
      },
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/1_28d2c3de-f401-442f-9545-995aa751d3a3.jpg?v=1707365986",
        alt: "PS4 Pro 1TB console front",
        width: 1200,
        height: 1200,
      },
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/2_8b1157b2-8fb5-44ab-af9a-88ad2975a004.jpg?v=1707365986",
        alt: "PS4 Pro 1TB with DualShock",
        width: 1200,
        height: 1200,
      },
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/3_6c926b56-df86-409c-9dd1-20e6f1221bad.jpg?v=1707365986",
        alt: "PS4 Pro 1TB side view",
        width: 1200,
        height: 1200,
      },
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/4_44b040fd-cf50-4a93-87f2-56d2e0c02ad8.jpg?v=1707365986",
        alt: "PS4 Pro 1TB ports",
        width: 1200,
        height: 1200,
      },
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/5_82b804a4-618c-4828-8493-cecfc912e662.jpg?v=1707365986",
        alt: "PS4 Pro 1TB detail",
        width: 1200,
        height: 1200,
      },
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/6_3e588251-0ffd-46bc-befb-b768c291b7bb.jpg?v=1707365986",
        alt: "PS4 Pro 1TB package view",
        width: 1200,
        height: 1200,
      },
    ],
    variants: [
      {
        id: "var-ps4-pro-1tb",
        title: "Default",
        sku: "PTPK-PS4-PRO-1TB",
        price: pkr(88000),
        compareAtPrice: pkr(98000),
        available: true,
        quantityAvailable: 6,
      },
    ],
    specs: [
      { label: "Storage", value: "1TB HDD" },
      { label: "Resolution", value: "Up to 4K" },
      { label: "HDR", value: "Yes" },
      { label: "Status", value: "Official (Non-jailbreak)" },
    ],
    compatibility: ["PlayStation 4", "PlayStation 4 Pro"],
    featured: true,
    bestSeller: false,
    newArrival: true,
    onDeal: true,
    dealEndsAt: new Date(Date.now() + 1000 * 60 * 60 * 72).toISOString(),
    shippingInfo: "Free shipping on orders over Rs. 15,000. Dispatch within 24 hours.",
    createdAt: "2026-07-26T13:00:00Z",
  },
  {
    id: "prod-2",
    handle: "xbox-series-x-video-game-console-black",
    title: "Xbox Series X Video Game Console, Black",
    brand: "Microsoft",
    description:
      "Introducing Xbox Series X, the fastest, most powerful Xbox ever. Play thousands of titles from four generations — all games look and play best on Xbox Series X. Xbox Velocity Architecture pairs a custom SSD with integrated software for faster gameplay and reduced load times. Quick Resume lets you move between games instantly. Enjoy unmatched 12 teraflops of graphic processing power, true 4K gaming at up to 120 FPS, and advanced 3D spatial sound. Backward compatible with thousands of games. Xbox Smart Delivery ensures you play the best available version of your game.",
    category: "xbox-series-x",
    categoryPath: ["xbox", "xbox-series-x", "consoles"],
    platform: ["Xbox Series X|S"],
    tags: ["console", "xbox", "featured", "consoles"],
    condition: "new",
    rating: 4.8,
    reviewCount: 312,
    images: [
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/Xbox-Series-X-1.jpg?v=1734508868",
        alt: "Xbox Series X Video Game Console Black",
        width: 1200,
        height: 1200,
      },
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/0BE229FA-1308-44C2-A5DD-BC4E3B38F42C.jpg?v=1734508868",
        alt: "Xbox Series X front view",
        width: 1200,
        height: 1200,
      },
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/07D9C72C-3BB7-4C78-A57D-B363BA80E502.jpg?v=1734508869",
        alt: "Xbox Series X with controller",
        width: 1200,
        height: 1200,
      },
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/59FEDF7D-B66F-404C-ACD3-78023A931423.jpg?v=1734508869",
        alt: "Xbox Series X side view",
        width: 1200,
        height: 1200,
      },
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/2_f079828d-5804-4a55-81d8-ba4f9e03f167.jpg?v=1734508868",
        alt: "Xbox Series X ports",
        width: 1200,
        height: 1200,
      },
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/3_99e09014-7323-4624-a87e-a90cd506e079.jpg?v=1734508868",
        alt: "Xbox Series X detail",
        width: 1200,
        height: 1200,
      },
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/4_d768c8f1-31c8-49d0-86fb-82a14b76bf82.jpg?v=1734508868",
        alt: "Xbox Series X console angle",
        width: 1200,
        height: 1200,
      },
      {
        url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/5_df6defc2-2e4f-4498-8170-599b1ab5f801.jpg?v=1734508868",
        alt: "Xbox Series X package view",
        width: 1200,
        height: 1200,
      },
    ],
    variants: [
      {
        id: "var-2",
        title: "Default",
        sku: "PTPK-XBX-SX-1TB",
        price: pkr(245000),
        compareAtPrice: pkr(248000),
        available: true,
        quantityAvailable: 10,
      },
    ],
    specs: [
      { label: "Storage", value: "1TB SSD" },
      { label: "Memory", value: "16 GB" },
      { label: "GPU", value: "12 teraflops" },
      { label: "Resolution", value: "True 4K" },
      { label: "Frame Rate", value: "Up to 120 FPS" },
      { label: "Processor", value: "Custom Zen 2 · 3.66 GHz" },
      { label: "Color", value: "Black" },
    ],
    compatibility: ["Xbox Series X"],
    featured: true,
    bestSeller: true,
    newArrival: true,
    onDeal: true,
    dealEndsAt: new Date(Date.now() + 1000 * 60 * 60 * 36).toISOString(),
    shippingInfo: "Free shipping on orders over Rs. 15,000. Dispatch within 24 hours.",
    createdAt: "2026-06-20T10:00:00Z",
  },
  {
    id: "prod-ps4-slim-1tb-jailbreak",
    handle: "playstation-4-slim-1tb-jail-break-filled-with-games",
    title: "Playstation 4 SLIM 1TB Jailbreak Filled With Games",
    brand: "Sony",
    description:
      "PS4 Slim 1TB with GoldHEN / custom firmware installed — fully jailbroken and ready for homebrew, emulators, and custom themes. Massive 1TB storage with a pre-installed library of popular titles. Custom game requests available. Quieter and more compact than the original PS4.",
    category: "ps4-consoles",
    categoryPath: ["playstation", "ps4-consoles", "consoles"],
    platform: ["PlayStation 4"],
    tags: ["console", "ps4", "jailbreak", "consoles"],
    condition: "refurbished",
    rating: 4.5,
    reviewCount: 74,
    images: [
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/files/Ps4-slim-500-Gb-Front_5946ef26-4399-4e87-984a-999489f5782b.jpg?v=1762942082", alt: "PS4 Slim 1TB Jailbreak", width: 1200, height: 1200 },
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/files/1-1_56a4e73d-aeae-4856-8f22-b4def109a193.jpg?v=1762942082", alt: "PS4 Slim 1TB Jailbreak front", width: 1200, height: 1200 },
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/files/PS4-SLIM_eae98227-d483-4e6f-8308-5fa16de1180a.webp?v=1762942083", alt: "PS4 Slim 1TB Jailbreak console", width: 1200, height: 1200 },
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/files/2-1_4b1415de-4e0f-467c-b339-f6f4b809b541.jpg?v=1762942082", alt: "PS4 Slim 1TB Jailbreak with controller", width: 1200, height: 1200 },
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/files/3-1_49f0f8f2-3046-40f8-9949-42c78c9ddba6.jpg?v=1762942083", alt: "PS4 Slim 1TB Jailbreak side", width: 1200, height: 1200 },
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/files/4-1_4e208d2c-1cc6-4f76-b044-b82447ae5d5e.jpg?v=1762942083", alt: "PS4 Slim 1TB Jailbreak detail", width: 1200, height: 1200 },
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/files/5-1_42e4b58f-ada6-4e54-b250-837254101680.jpg?v=1762942082", alt: "PS4 Slim 1TB Jailbreak ports", width: 1200, height: 1200 },
    ],
    variants: [
      {
        id: "var-ps4-slim-1tb-jailbreak",
        title: "Default",
        sku: "PTPK-PS4-SLIM-1TB-JB",
        price: pkr(85000),
        compareAtPrice: pkr(88000),
        available: true,
        quantityAvailable: 5,
      },
    ],
    specs: [
      { label: "Storage", value: "1TB HDD" },
      { label: "Firmware", value: "Jailbreak / GoldHEN" },
      { label: "Form Factor", value: "Slim" },
    ],
    compatibility: ["PlayStation 4"],
    featured: true,
    newArrival: true,
    onDeal: true,
    shippingInfo: "Free shipping on orders over Rs. 15,000. Dispatch within 24 hours.",
    createdAt: "2026-07-26T14:00:00Z",
  },
  {
    id: "prod-ps4-slim-1tb-official",
    handle: "playstation-4-slim-1tb-standard-official",
    title: "Playstation 4 SLIM 1TB Standard Official (Non-jailbreak)",
    brand: "Sony",
    description:
      "Official PlayStation 4 Slim 1TB (non-jailbreak) with dynamic connected gaming, DualShock 4 controller innovations, suspend mode for instant resume, and SHARE button capture. Compact slim design with 1TB storage.",
    category: "ps4-consoles",
    categoryPath: ["playstation", "ps4-consoles", "consoles"],
    platform: ["PlayStation 4"],
    tags: ["console", "ps4", "official", "consoles"],
    condition: "refurbished",
    rating: 4.6,
    reviewCount: 112,
    images: [
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/files/Ps4-slim-500-Gb-Front_6031872e-abf1-40ae-9fe4-e439c5c4d908.jpg?v=1762942609", alt: "PS4 Slim 1TB Official", width: 1200, height: 1200 },
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/files/1-1_a971cc0f-e247-4387-af67-dec44a8648fd.jpg?v=1762942609", alt: "PS4 Slim 1TB Official front", width: 1200, height: 1200 },
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/files/2-1_768c07b8-2369-456d-8040-02390297b0fe.jpg?v=1762942609", alt: "PS4 Slim 1TB Official with controller", width: 1200, height: 1200 },
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/files/3-1_7ee65da7-685b-42ee-af3f-7cf8469bffb7.jpg?v=1762942609", alt: "PS4 Slim 1TB Official side", width: 1200, height: 1200 },
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/files/4-1_6bcfd199-abf2-4fc1-ae84-a141c4fab295.jpg?v=1762942609", alt: "PS4 Slim 1TB Official detail", width: 1200, height: 1200 },
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/files/5-1_ad122875-dd70-4148-b218-4efa804b1348.jpg?v=1762942609", alt: "PS4 Slim 1TB Official ports", width: 1200, height: 1200 },
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/files/PS4-SLIM_bd47424d-4bee-4424-bdca-9fa13ab49c37.webp?v=1762942609", alt: "PS4 Slim 1TB Official console", width: 1200, height: 1200 },
    ],
    variants: [
      {
        id: "var-ps4-slim-1tb-official",
        title: "Default",
        sku: "PTPK-PS4-SLIM-1TB-OFF",
        price: pkr(75000),
        compareAtPrice: pkr(85000),
        available: true,
        quantityAvailable: 6,
      },
    ],
    specs: [
      { label: "Storage", value: "1TB HDD" },
      { label: "Status", value: "Official (Non-jailbreak)" },
      { label: "Form Factor", value: "Slim" },
    ],
    compatibility: ["PlayStation 4"],
    featured: true,
    newArrival: true,
    onDeal: true,
    shippingInfo: "Free shipping on orders over Rs. 15,000. Dispatch within 24 hours.",
    createdAt: "2026-07-26T14:10:00Z",
  },
  {
    id: "prod-ps4-slim-500gb",
    handle: "playstation-4-500-gb-slim-model-refurbished",
    title: "Playstation 4 Slim 500 GB Standard Official (Non-jailbreak)",
    brand: "Sony",
    description:
      "Refurbished PlayStation 4 Slim 500GB official (non-jailbreak). Connected gaming with DualShock 4, suspend mode, SHARE capture, and social features — compact slim form factor.",
    category: "ps4-consoles",
    categoryPath: ["playstation", "ps4-consoles", "consoles"],
    platform: ["PlayStation 4"],
    tags: ["console", "ps4", "refurbished", "consoles"],
    condition: "refurbished",
    rating: 4.4,
    reviewCount: 89,
    images: [
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/Ps4-slim-500-Gb-Front.jpg?v=1707358605", alt: "PS4 Slim 500GB", width: 1200, height: 1200 },
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/PS4-SLIM.webp?v=1707358605", alt: "PS4 Slim 500GB console", width: 1200, height: 1200 },
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/1-1_37ec3d5f-46ee-42ea-b5bf-fc065c4f8ec6.jpg?v=1707358605", alt: "PS4 Slim 500GB front", width: 1200, height: 1200 },
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/2-1_4fdb690e-ab26-469c-86a9-ac4ec254fc7f.jpg?v=1707358605", alt: "PS4 Slim 500GB with controller", width: 1200, height: 1200 },
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/3-1_dc4e9736-01ab-489f-bbfb-96baf7883dc7.jpg?v=1707358605", alt: "PS4 Slim 500GB side", width: 1200, height: 1200 },
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/4-1_daa6bd40-45a4-4dbf-977f-b6deaccdc553.jpg?v=1707358605", alt: "PS4 Slim 500GB detail", width: 1200, height: 1200 },
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/5-1_31b7e3f8-0be2-4cc6-bf55-16f882965eb0.jpg?v=1707358605", alt: "PS4 Slim 500GB ports", width: 1200, height: 1200 },
    ],
    variants: [
      {
        id: "var-ps4-slim-500gb",
        title: "Default",
        sku: "PTPK-PS4-SLIM-500GB",
        price: pkr(68000),
        compareAtPrice: pkr(75000),
        available: true,
        quantityAvailable: 7,
      },
    ],
    specs: [
      { label: "Storage", value: "500GB HDD" },
      { label: "Status", value: "Official (Non-jailbreak)" },
      { label: "Condition", value: "Refurbished" },
      { label: "Form Factor", value: "Slim" },
    ],
    compatibility: ["PlayStation 4"],
    featured: false,
    newArrival: true,
    onDeal: true,
    shippingInfo: "Free shipping on orders over Rs. 15,000. Dispatch within 24 hours.",
    createdAt: "2026-07-26T14:20:00Z",
  },
  {
    id: "prod-xbox-360-fat-320gb",
    handle: "xbox-360-fat-320gb-filled-with-60-plus-games",
    title: "Xbox 360 FAT 320GB (filled with 60 plus games)",
    brand: "Microsoft",
    description:
      "Xbox 360 FAT 320GB filled with 60+ games. Sleek home entertainment console with 320GB hard drive, Kinect-ready port (Kinect not included), wireless controller support, and composite A/V cable for standard-definition TVs.",
    category: "xbox-360",
    categoryPath: ["xbox", "xbox-360", "consoles"],
    platform: ["Xbox 360"],
    tags: ["console", "xbox", "xbox-360", "consoles"],
    condition: "refurbished",
    rating: 4.3,
    reviewCount: 56,
    images: [
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/files/WhatsApp_Image_2025-03-11_at_3.55.47_PM_1.jpg?v=1741690794", alt: "Xbox 360 FAT 320GB", width: 1200, height: 1200 },
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/files/WhatsApp_Image_2025-03-11_at_3.55.46_PM.jpg?v=1741690794", alt: "Xbox 360 FAT 320GB front", width: 1200, height: 1200 },
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/files/WhatsApp_Image_2025-03-11_at_3.55.47_PM.jpg?v=1741690794", alt: "Xbox 360 FAT 320GB side", width: 1200, height: 1200 },
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/31LBFaT8-3L._AA500___80193.jpg?v=1741690794", alt: "Xbox 360 FAT 320GB console", width: 500, height: 500 },
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/71DU7TF9cJL._AC_SL1500.jpg?v=1741690794", alt: "Xbox 360 FAT 320GB package", width: 1500, height: 1500 },
    ],
    variants: [
      {
        id: "var-xbox-360-fat-320gb",
        title: "Default",
        sku: "PTPK-X360-FAT-320GB",
        price: pkr(31500),
        available: true,
        quantityAvailable: 4,
      },
    ],
    specs: [
      { label: "Storage", value: "320GB HDD" },
      { label: "Games", value: "60+ preloaded" },
      { label: "Form Factor", value: "FAT" },
      { label: "Kinect", value: "Ready (sold separately)" },
    ],
    compatibility: ["Xbox 360"],
    featured: false,
    newArrival: true,
    onDeal: false,
    shippingInfo: "Free shipping on orders over Rs. 15,000. Dispatch within 24 hours.",
    createdAt: "2026-07-26T14:30:00Z",
  },
  {
    id: "prod-xbox-one-500gb",
    handle: "xbox-one-500-gb-console-black",
    title: "Xbox One 500 GB Console Black",
    brand: "Microsoft",
    description:
      "Xbox One 500GB Black — exclusive games, advanced multiplayer, Smart Match, gameplay sharing and live broadcast, plus apps like Netflix side-by-side with Snap. Entertainment and gaming in one black console.",
    category: "xbox-one",
    categoryPath: ["xbox", "xbox-one", "consoles"],
    platform: ["Xbox One"],
    tags: ["console", "xbox", "xbox-one", "consoles"],
    condition: "refurbished",
    rating: 4.4,
    reviewCount: 67,
    images: [
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/1-2_6f10f61f-1c5f-4900-86a5-73ba21977955.jpg?v=1741020411", alt: "Xbox One 500GB Black", width: 1200, height: 1200 },
      { url: "https://cdn.shopify.com/s/files/1/0860/1636/0729/products/2-3_d4cc7148-0d91-416d-9d0c-6f5acff21049.jpg?v=1741020410", alt: "Xbox One 500GB Black angle", width: 1200, height: 1200 },
    ],
    variants: [
      {
        id: "var-xbox-one-500gb",
        title: "Default",
        sku: "PTPK-XONE-500GB",
        price: pkr(50000),
        compareAtPrice: pkr(55000),
        available: true,
        quantityAvailable: 5,
      },
    ],
    specs: [
      { label: "Storage", value: "500GB" },
      { label: "Color", value: "Black" },
      { label: "Platform", value: "Xbox One" },
    ],
    compatibility: ["Xbox One"],
    featured: false,
    newArrival: true,
    onDeal: true,
    shippingInfo: "Free shipping on orders over Rs. 15,000. Dispatch within 24 hours.",
    createdAt: "2026-07-26T14:40:00Z",
  },
  {
    id: "prod-3",
    handle: "nintendo-switch-oled-white",
    title: "Nintendo Switch OLED White",
    brand: "Nintendo",
    description:
      "Vibrant 7-inch OLED screen, enhanced audio, and a wide adjustable stand for tabletop play.",
    category: "nintendo-switch-oled",
    categoryPath: ["nintendo", "nintendo-switch-oled"],
    platform: ["Nintendo Switch"],
    tags: ["console", "nintendo", "oled"],
    condition: "new",
    rating: 4.9,
    reviewCount: 501,
    images: [img("photo-1578303517154-48091adcdb15", "Nintendo Switch OLED")],
    variants: [
      {
        id: "var-3",
        title: "White",
        sku: "PTPK-NSW-OLED-WHT",
        price: pkr(94999),
        compareAtPrice: pkr(99999),
        available: true,
        quantityAvailable: 32,
      },
    ],
    specs: [
      { label: "Screen", value: "7-inch OLED" },
      { label: "Storage", value: "64GB" },
      { label: "Modes", value: "TV, Tabletop, Handheld" },
    ],
    compatibility: ["Nintendo Switch", "Nintendo Switch OLED"],
    featured: true,
    newArrival: true,
    bestSeller: true,
    createdAt: "2026-07-10T10:00:00Z",
  },
  {
    id: "prod-4",
    handle: "dualsense-midnight-black",
    title: "DualSense Wireless Controller Midnight Black",
    brand: "Sony",
    description:
      "Feel every moment with haptic feedback, adaptive triggers, and a built-in microphone.",
    category: "ps5-controllers",
    categoryPath: ["playstation", "ps5-controllers"],
    platform: ["PlayStation 5"],
    tags: ["controller", "dualsense"],
    condition: "new",
    rating: 4.7,
    reviewCount: 890,
    images: [img("photo-1593305841991-05c297ba4575", "DualSense controller")],
    variants: [
      {
        id: "var-4",
        title: "Midnight Black",
        sku: "PTPK-DS-BLK",
        price: pkr(21999),
        compareAtPrice: pkr(24999),
        available: true,
        quantityAvailable: 120,
      },
    ],
    specs: [
      { label: "Connectivity", value: "Bluetooth / USB-C" },
      { label: "Battery", value: "Built-in rechargeable" },
      { label: "Features", value: "Haptics, Adaptive Triggers" },
    ],
    compatibility: ["PlayStation 5", "PlayStation 5 Slim", "PlayStation 5 Pro", "PC"],
    featured: true,
    bestSeller: true,
    onDeal: true,
    dealEndsAt: new Date(Date.now() + 1000 * 60 * 60 * 20).toISOString(),
    createdAt: "2026-05-15T10:00:00Z",
  },
  {
    id: "prod-5",
    handle: "xbox-wireless-controller-carbon",
    title: "Xbox Wireless Controller Carbon Black",
    brand: "Microsoft",
    description: "Textured grip, hybrid D-pad, and Bluetooth connectivity for Xbox and Windows.",
    category: "xbox-controllers",
    categoryPath: ["xbox", "xbox-controllers"],
    platform: ["Xbox Series X|S", "Xbox One", "PC"],
    tags: ["controller", "xbox"],
    condition: "new",
    rating: 4.6,
    reviewCount: 654,
    images: [img("photo-1612287230202-1ff1d85d1bdf", "Xbox wireless controller")],
    variants: [
      {
        id: "var-5",
        title: "Carbon Black",
        sku: "PTPK-XBX-CTRL-CB",
        price: pkr(18999),
        available: true,
        quantityAvailable: 95,
      },
    ],
    specs: [
      { label: "Connectivity", value: "Xbox Wireless / Bluetooth" },
      { label: "Compatibility", value: "Xbox Series X|S, Xbox One, PC" },
    ],
    compatibility: ["Xbox Series X", "Xbox Series S", "Xbox One", "PC"],
    bestSeller: true,
    createdAt: "2026-04-10T10:00:00Z",
  },
  {
    id: "prod-6",
    handle: "razer-blackshark-v2-pro",
    title: "Razer BlackShark V2 Pro Wireless Headset",
    brand: "Razer",
    description:
      "Esports-tuned wireless headset with TriForce Titanium drivers and HyperSpeed wireless.",
    category: "gaming-headsets",
    categoryPath: ["accessories", "gaming-headsets"],
    platform: ["PlayStation 5", "Xbox Series X|S", "PC", "Nintendo Switch"],
    tags: ["headset", "wireless"],
    condition: "new",
    rating: 4.8,
    reviewCount: 277,
    images: [img("photo-1599669454699-248893623440", "Gaming headset")],
    variants: [
      {
        id: "var-6",
        title: "Black",
        sku: "PTPK-RZR-BSV2P",
        price: pkr(44999),
        compareAtPrice: pkr(52999),
        available: true,
        quantityAvailable: 40,
      },
    ],
    specs: [
      { label: "Drivers", value: "50mm TriForce Titanium" },
      { label: "Wireless", value: "Razer HyperSpeed" },
      { label: "Battery", value: "Up to 70 hours" },
    ],
    compatibility: ["PC", "PlayStation 5", "Xbox Series X", "Xbox Series S", "Nintendo Switch"],
    featured: true,
    onDeal: true,
    dealEndsAt: new Date(Date.now() + 1000 * 60 * 60 * 12).toISOString(),
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "prod-7",
    handle: "logitech-g-pro-x-keyboard",
    title: "Logitech G Pro X TKL Mechanical Keyboard",
    brand: "Logitech",
    description: "Tournament-ready tenkeyless keyboard with swappable GX switches and RGB.",
    category: "gaming-keyboards",
    categoryPath: ["accessories", "gaming-keyboards"],
    platform: ["PC"],
    tags: ["keyboard", "mechanical"],
    condition: "new",
    rating: 4.7,
    reviewCount: 198,
    images: [img("photo-1511467687858-23d96c32e4ae", "Mechanical gaming keyboard")],
    variants: [
      {
        id: "var-7",
        title: "GX Blue",
        sku: "PTPK-LOG-GPROX-TKL",
        price: pkr(32999),
        compareAtPrice: pkr(37999),
        available: true,
        quantityAvailable: 55,
      },
    ],
    specs: [
      { label: "Form Factor", value: "TKL" },
      { label: "Switches", value: "Hot-swappable GX" },
      { label: "Lighting", value: "LIGHTSYNC RGB" },
    ],
    compatibility: ["PC"],
    newArrival: true,
    createdAt: "2026-07-12T10:00:00Z",
  },
  {
    id: "prod-8",
    handle: "razer-viper-v3-pro",
    title: "Razer Viper V3 Pro Wireless Mouse",
    brand: "Razer",
    description: "Ultra-lightweight esports mouse with Focus Pro 30K optical sensor.",
    category: "gaming-mice",
    categoryPath: ["accessories", "gaming-mice"],
    platform: ["PC"],
    tags: ["mouse", "wireless", "esports"],
    condition: "new",
    rating: 4.9,
    reviewCount: 143,
    images: [img("photo-1527864550417-7fd91fc51a46", "Gaming mouse")],
    variants: [
      {
        id: "var-8",
        title: "Black",
        sku: "PTPK-RZR-VPR-V3",
        price: pkr(39999),
        available: true,
        quantityAvailable: 48,
      },
    ],
    specs: [
      { label: "Weight", value: "54g" },
      { label: "Sensor", value: "Focus Pro 30K" },
      { label: "Battery", value: "Up to 95 hours" },
    ],
    compatibility: ["PC"],
    featured: true,
    newArrival: true,
    createdAt: "2026-07-15T10:00:00Z",
  },
  {
    id: "prod-9",
    handle: "secretlab-titan-evo-2026",
    title: "Secretlab TITAN Evo Gaming Chair",
    brand: "Secretlab",
    description: "Ergonomic gaming chair with magnetic memory foam pillow and 4-way L-Lumbar.",
    category: "gaming-chairs",
    categoryPath: ["accessories", "gaming-chairs"],
    platform: ["PC", "PlayStation 5", "Xbox Series X|S"],
    tags: ["chair", "ergonomic"],
    condition: "new",
    rating: 4.8,
    reviewCount: 89,
    images: [img("photo-1595428774223-ef526ba8f9cf", "Gaming chair")],
    variants: [
      {
        id: "var-9",
        title: "Stealth",
        sku: "PTPK-SL-TITAN-EVO",
        price: pkr(129999),
        compareAtPrice: pkr(149999),
        available: true,
        quantityAvailable: 12,
      },
    ],
    specs: [
      { label: "Size", value: "Regular" },
      { label: "Material", value: "NEO Hybrid Leatherette" },
      { label: "Warranty", value: "5 years" },
    ],
    compatibility: ["Universal"],
    onDeal: true,
    dealEndsAt: new Date(Date.now() + 1000 * 60 * 60 * 72).toISOString(),
    createdAt: "2026-05-01T10:00:00Z",
  },
  {
    id: "prod-10",
    handle: "astro-bot-ps5",
    title: "ASTRO BOT — PS5 Physical Edition",
    brand: "Sony",
    description: "Award-winning platforming adventure exclusive to PlayStation 5.",
    category: "ps5-games",
    categoryPath: ["games", "ps5-games"],
    platform: ["PlayStation 5"],
    tags: ["game", "exclusive", "new-release"],
    condition: "new",
    rating: 4.9,
    reviewCount: 1204,
    images: [img("photo-1552820728-8b83bb6b773f", "PS5 game case")],
    variants: [
      {
        id: "var-10",
        title: "Physical",
        sku: "PTPK-GAME-ASTRO-PS5",
        price: pkr(12999),
        available: true,
        quantityAvailable: 200,
      },
    ],
    specs: [
      { label: "Genre", value: "Platformer" },
      { label: "Players", value: "1" },
      { label: "Format", value: "Blu-ray Disc" },
    ],
    compatibility: ["PlayStation 5", "PlayStation 5 Slim", "PlayStation 5 Pro"],
    bestSeller: true,
    newArrival: true,
    featured: true,
    createdAt: "2026-07-18T10:00:00Z",
  },
  {
    id: "prod-11",
    handle: "halo-infinite-xbox",
    title: "Halo Infinite — Xbox Series X|S",
    brand: "Microsoft",
    description: "Master Chief returns in the legendary open-world Halo campaign and multiplayer.",
    category: "xbox-games",
    categoryPath: ["games", "xbox-games"],
    platform: ["Xbox Series X|S", "Xbox One"],
    tags: ["game", "fps"],
    condition: "new",
    rating: 4.5,
    reviewCount: 780,
    images: [img("photo-1511512578047-dfb367046420", "Xbox game")],
    variants: [
      {
        id: "var-11",
        title: "Physical",
        sku: "PTPK-GAME-HALO-XBX",
        price: pkr(7999),
        compareAtPrice: pkr(9999),
        available: true,
        quantityAvailable: 150,
      },
    ],
    specs: [
      { label: "Genre", value: "FPS" },
      { label: "Players", value: "1–24" },
    ],
    compatibility: ["Xbox Series X", "Xbox Series S", "Xbox One"],
    onDeal: true,
    dealEndsAt: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString(),
    createdAt: "2026-03-01T10:00:00Z",
  },
  {
    id: "prod-12",
    handle: "zelda-tears-of-the-kingdom",
    title: "The Legend of Zelda: Tears of the Kingdom",
    brand: "Nintendo",
    description: "Explore Hyrule and the skies above in this epic Nintendo Switch adventure.",
    category: "nintendo-switch-games",
    categoryPath: ["games", "nintendo-games"],
    platform: ["Nintendo Switch"],
    tags: ["game", "adventure", "best-seller"],
    condition: "new",
    rating: 5.0,
    reviewCount: 2100,
    images: [
      {
        url: "https://upload.wikimedia.org/wikipedia/en/f/fb/The_Legend_of_Zelda_Tears_of_the_Kingdom_cover.jpg",
        alt: "The Legend of Zelda: Tears of the Kingdom — official box art",
        width: 600,
        height: 900,
      },
    ],
    variants: [
      {
        id: "var-12",
        title: "Physical",
        sku: "PTPK-GAME-ZELDA-TOTK",
        price: pkr(14999),
        available: true,
        quantityAvailable: 180,
      },
    ],
    specs: [
      { label: "Genre", value: "Action-Adventure" },
      { label: "Players", value: "1" },
    ],
    compatibility: ["Nintendo Switch", "Nintendo Switch OLED"],
    bestSeller: true,
    featured: true,
    createdAt: "2026-02-01T10:00:00Z",
  },
  {
    id: "prod-13",
    handle: "steelseries-arctis-nova-pro",
    title: "SteelSeries Arctis Nova Pro Wireless",
    brand: "SteelSeries",
    description: "Hi-Fi drivers, active noise cancellation, and dual wireless with hot-swap batteries.",
    category: "gaming-headsets",
    categoryPath: ["accessories", "gaming-headsets"],
    platform: ["PlayStation 5", "PC", "Xbox Series X|S"],
    tags: ["headset", "premium"],
    condition: "new",
    rating: 4.7,
    reviewCount: 166,
    images: [img("photo-1618366712010-f4ae9c647dcb", "Premium gaming headset")],
    variants: [
      {
        id: "var-13",
        title: "Black",
        sku: "PTPK-SS-NOVA-PRO",
        price: pkr(69999),
        compareAtPrice: pkr(79999),
        available: true,
        quantityAvailable: 22,
      },
    ],
    specs: [
      { label: "ANC", value: "Active Noise Cancellation" },
      { label: "Battery", value: "Hot-swappable dual batteries" },
    ],
    compatibility: ["PC", "PlayStation 5", "Xbox Series X", "Xbox Series S"],
    newArrival: true,
    createdAt: "2026-07-08T10:00:00Z",
  },
  {
    id: "prod-14",
    handle: "ps5-pulse-elite-headset",
    title: "PULSE Elite Wireless Headset",
    brand: "Sony",
    description: "PlayStation official wireless headset with retractable microphone and Tempest 3D Audio.",
    category: "playstation-headsets",
    categoryPath: ["playstation", "playstation-headsets"],
    platform: ["PlayStation 5"],
    tags: ["headset", "official"],
    condition: "new",
    rating: 4.6,
    reviewCount: 320,
    images: [img("photo-1546435770-a3e426bf472b", "PlayStation headset")],
    variants: [
      {
        id: "var-14",
        title: "White",
        sku: "PTPK-PS5-PULSE-ELT",
        price: pkr(34999),
        available: true,
        quantityAvailable: 60,
      },
    ],
    specs: [
      { label: "Audio", value: "Tempest 3D AudioTech" },
      { label: "Mic", value: "Retractable" },
    ],
    compatibility: ["PlayStation 5", "PlayStation 5 Slim", "PlayStation 5 Pro", "PC"],
    bestSeller: true,
    createdAt: "2026-04-20T10:00:00Z",
  },
  {
    id: "prod-15",
    handle: "fifa-26-ps5",
    title: "EA SPORTS FC 26 — PS5",
    brand: "EA",
    description: "The latest football simulation with HyperMotion and career modes.",
    category: "ps5-games",
    categoryPath: ["games", "ps5-games", "new-releases"],
    platform: ["PlayStation 5"],
    tags: ["game", "sports", "fifa", "ps5-cd", "top-pakistan"],
    condition: "new",
    rating: 4.3,
    reviewCount: 450,
    images: [img("photo-1574629810360-7efbbe195018", "Football video game")],
    variants: [
      {
        id: "var-15",
        title: "Standard",
        sku: "PTPK-GAME-FC26-PS5",
        price: pkr(15999),
        available: true,
        quantityAvailable: 300,
      },
    ],
    specs: [
      { label: "Genre", value: "Sports" },
      { label: "Players", value: "1–4" },
      { label: "Format", value: "Blu-ray Disc (PS5)" },
    ],
    compatibility: ["PlayStation 5", "PlayStation 5 Slim", "PlayStation 5 Pro"],
    newArrival: true,
    featured: true,
    bestSeller: true,
    createdAt: "2026-07-20T10:00:00Z",
  },
  {
    id: "prod-16",
    handle: "hyperx-quadcast-s",
    title: "HyperX QuadCast S USB Microphone",
    brand: "HyperX",
    description: "RGB condenser mic with anti-vibration shock mount for streaming and content.",
    category: "gaming-microphones",
    categoryPath: ["accessories", "gaming-microphones"],
    platform: ["PC", "PlayStation 5"],
    tags: ["microphone", "streaming"],
    condition: "new",
    rating: 4.7,
    reviewCount: 211,
    images: [img("photo-1590602847861-f357a9332bbc", "USB gaming microphone")],
    variants: [
      {
        id: "var-16",
        title: "RGB",
        sku: "PTPK-HX-QC-S",
        price: pkr(27999),
        compareAtPrice: pkr(31999),
        available: true,
        quantityAvailable: 35,
      },
    ],
    specs: [
      { label: "Polar Patterns", value: "4" },
      { label: "Connection", value: "USB" },
    ],
    compatibility: ["PC", "PlayStation 5", "Mac"],
    onDeal: true,
    dealEndsAt: new Date(Date.now() + 1000 * 60 * 60 * 18).toISOString(),
    createdAt: "2026-06-12T10:00:00Z",
  },
  {
    id: "prod-17",
    handle: "seagate-2tb-xbox-expansion",
    title: "Seagate 2TB Storage Expansion Card for Xbox",
    brand: "Seagate",
    description: "Official Xbox Series X|S storage expansion — plug in and play.",
    category: "storage-devices",
    categoryPath: ["accessories", "storage-devices"],
    platform: ["Xbox Series X|S"],
    tags: ["storage", "xbox"],
    condition: "new",
    rating: 4.8,
    reviewCount: 402,
    images: [img("photo-1597872200969-2b65d56bd16b", "SSD storage device")],
    variants: [
      {
        id: "var-17",
        title: "2TB",
        sku: "PTPK-SG-XBX-2TB",
        price: pkr(54999),
        available: true,
        quantityAvailable: 28,
      },
    ],
    specs: [
      { label: "Capacity", value: "2TB" },
      { label: "Interface", value: "Xbox Expansion Slot" },
    ],
    compatibility: ["Xbox Series X", "Xbox Series S"],
    createdAt: "2026-05-22T10:00:00Z",
  },
  {
    id: "prod-18",
    handle: "ps5-dualsense-charging-station",
    title: "DualSense Charging Station",
    brand: "Sony",
    description: "Charge up to two DualSense controllers simultaneously with click-in docking.",
    category: "charging-stations",
    categoryPath: ["accessories", "charging-stations"],
    platform: ["PlayStation 5"],
    tags: ["charger", "accessory"],
    condition: "new",
    rating: 4.5,
    reviewCount: 560,
    images: [img("photo-1606144042614-b2417e99c4e3", "Controller charging station")],
    variants: [
      {
        id: "var-18",
        title: "Default",
        sku: "PTPK-PS5-DS-CHG",
        price: pkr(8999),
        compareAtPrice: pkr(10999),
        available: true,
        quantityAvailable: 75,
      },
    ],
    specs: [
      { label: "Slots", value: "2" },
      { label: "Cable", value: "Included AC adaptor" },
    ],
    compatibility: ["PlayStation 5 DualSense Controllers"],
    onDeal: true,
    dealEndsAt: new Date(Date.now() + 1000 * 60 * 60 * 8).toISOString(),
    createdAt: "2026-04-05T10:00:00Z",
  },
  {
    id: "prod-19",
    handle: "spiderman-2-preowned-ps5",
    title: "Marvel's Spider-Man 2 (Used)",
    brand: "Sony",
    description: "Certified used physical disc — tested and wiped, ready to swing.",
    category: "pre-owned-games",
    categoryPath: ["games", "pre-owned-games", "ps5-games"],
    platform: ["PlayStation 5"],
    tags: ["game", "pre-owned"],
    condition: "pre-owned",
    rating: 4.8,
    reviewCount: 95,
    images: [img("photo-1550745165-9bc0b252726f", "Used PS5 game")],
    variants: [
      {
        id: "var-19",
        title: "Used",
        sku: "PTPK-PO-SM2-PS5",
        price: pkr(6999),
        compareAtPrice: pkr(12999),
        available: true,
        quantityAvailable: 14,
      },
    ],
    specs: [
      { label: "Condition", value: "Used — Excellent" },
      { label: "Includes", value: "Game disc + case" },
    ],
    compatibility: ["PlayStation 5", "PlayStation 5 Slim", "PlayStation 5 Pro"],
    onDeal: true,
    dealEndsAt: new Date(Date.now() + 1000 * 60 * 60 * 40).toISOString(),
    createdAt: "2026-07-05T10:00:00Z",
  },
  {
    id: "prod-20",
    handle: "logitech-g29-racing-wheel",
    title: "Logitech G29 Driving Force Racing Wheel",
    brand: "Logitech",
    description: "Force feedback racing wheel and pedals for PlayStation and PC sim racing.",
    category: "gaming-wheels",
    categoryPath: ["accessories", "gaming-wheels"],
    platform: ["PlayStation 5", "PlayStation 4", "PC"],
    tags: ["wheel", "racing"],
    condition: "new",
    rating: 4.6,
    reviewCount: 340,
    images: [img("photo-1511512578047-dfb367046420", "Racing wheel")],
    variants: [
      {
        id: "var-20",
        title: "G29",
        sku: "PTPK-LOG-G29",
        price: pkr(79999),
        compareAtPrice: pkr(89999),
        available: true,
        quantityAvailable: 10,
      },
    ],
    specs: [
      { label: "Feedback", value: "Dual-motor force feedback" },
      { label: "Pedals", value: "Included" },
    ],
    compatibility: ["PlayStation 5", "PlayStation 4", "PC"],
    createdAt: "2026-03-18T10:00:00Z",
  },
  {
    id: "prod-21",
    handle: "xbox-series-s-512gb",
    title: "Xbox Series S 512GB",
    brand: "Microsoft",
    description: "Next-gen performance in the smallest Xbox ever — perfect for digital gaming.",
    category: "xbox-series-s",
    categoryPath: ["xbox", "xbox-series-s", "consoles"],
    platform: ["Xbox Series X|S"],
    tags: ["console", "digital"],
    condition: "new",
    rating: 4.6,
    reviewCount: 520,
    images: [img("photo-1605901309584-818e25995b6b", "Xbox Series S")],
    variants: [
      {
        id: "var-21",
        title: "512GB",
        sku: "PTPK-XBX-SS-512",
        price: pkr(99999),
        compareAtPrice: pkr(109999),
        available: true,
        quantityAvailable: 40,
      },
    ],
    specs: [
      { label: "Storage", value: "512GB SSD" },
      { label: "Resolution", value: "Up to 1440p" },
    ],
    compatibility: ["Xbox Series S"],
    featured: true,
    createdAt: "2026-06-28T10:00:00Z",
  },
  {
    id: "prod-22",
    handle: "joy-con-neon-pair",
    title: "Nintendo Switch Joy-Con Pair Neon Red/Blue",
    brand: "Nintendo",
    description: "Official Joy-Con controllers with HD rumble and motion IR camera.",
    category: "nintendo-switch-controllers",
    categoryPath: ["nintendo", "nintendo-switch-controllers"],
    platform: ["Nintendo Switch"],
    tags: ["controller", "joy-con"],
    condition: "new",
    rating: 4.4,
    reviewCount: 670,
    images: [img("photo-1578303517154-48091adcdb15", "Joy-Con controllers")],
    variants: [
      {
        id: "var-22",
        title: "Neon Red/Blue",
        sku: "PTPK-NSW-JC-NEON",
        price: pkr(18999),
        available: true,
        quantityAvailable: 88,
      },
    ],
    specs: [
      { label: "Features", value: "HD Rumble, IR Camera, Motion" },
    ],
    compatibility: ["Nintendo Switch", "Nintendo Switch OLED"],
    bestSeller: true,
    createdAt: "2026-05-30T10:00:00Z",
  },
  {
    id: "prod-23",
    handle: "toycompany-xxl-mousepad",
    title: "ToyCompany Velocity XXL Mouse Pad",
    brand: "ToyCompany",
    description: "Extended desk mat with stitched edges and low-friction weave for precision aim.",
    category: "gaming-mouse-pads",
    categoryPath: ["accessories", "gaming-mouse-pads"],
    platform: ["PC"],
    tags: ["mousepad", "desk-mat"],
    condition: "new",
    rating: 4.5,
    reviewCount: 88,
    images: [img("photo-1615663245857-ac93bb7c39e7", "Gaming mouse pad")],
    variants: [
      {
        id: "var-23",
        title: "XXL",
        sku: "PTPK-PAD-VEL-XXL",
        price: pkr(4999),
        compareAtPrice: pkr(6999),
        available: true,
        quantityAvailable: 200,
      },
    ],
    specs: [
      { label: "Size", value: "900 × 400 mm" },
      { label: "Surface", value: "Micro-weave cloth" },
    ],
    compatibility: ["Universal"],
    newArrival: true,
    onDeal: true,
    dealEndsAt: new Date(Date.now() + 1000 * 60 * 60 * 60).toISOString(),
    createdAt: "2026-07-19T10:00:00Z",
  },
  {
    id: "prod-24",
    handle: "hdmi-2-1-cable-3m",
    title: "Ultra High Speed HDMI 2.1 Cable 3m",
    brand: "ToyCompany",
    description: "8K/4K120 certified HDMI 2.1 cable for next-gen consoles and monitors.",
    category: "hdmi-cables",
    categoryPath: ["accessories", "hdmi-cables"],
    platform: ["PlayStation 5", "Xbox Series X|S", "PC", "Nintendo Switch"],
    tags: ["cable", "hdmi"],
    condition: "new",
    rating: 4.6,
    reviewCount: 230,
    images: [img("photo-1558618666-fcd25c85cd64", "HDMI cable")],
    variants: [
      {
        id: "var-24",
        title: "3m",
        sku: "PTPK-HDMI-21-3M",
        price: pkr(3499),
        available: true,
        quantityAvailable: 500,
      },
    ],
    specs: [
      { label: "Standard", value: "HDMI 2.1" },
      { label: "Bandwidth", value: "48 Gbps" },
    ],
    compatibility: ["PlayStation 5", "Xbox Series X", "Xbox Series S", "PC", "Nintendo Switch"],
    createdAt: "2026-01-15T10:00:00Z",
  },
  // —— Top PS5 CDs most ordered in the Pakistani market ——
  {
    id: "prod-25",
    handle: "gta-v-ps5",
    title: "Grand Theft Auto V — PS5 Disc",
    brand: "Rockstar",
    description:
      "Pakistan’s all-time favourite open-world classic on PS5. Physical disc with GTA Online — the most traded PS5 CD in local markets.",
    category: "ps5-games",
    categoryPath: ["games", "ps5-games", "best-sellers"],
    platform: ["PlayStation 5"],
    tags: ["game", "ps5-cd", "top-pakistan", "best-seller"],
    condition: "new",
    rating: 4.9,
    reviewCount: 3200,
    images: [img("photo-1493711662062-fa541adb3fc8", "GTA V PS5 game disc")],
    variants: [
      {
        id: "var-25",
        title: "Physical Disc",
        sku: "PTPK-GAME-GTAV-PS5",
        price: pkr(6699),
        compareAtPrice: pkr(7999),
        available: true,
        quantityAvailable: 220,
      },
    ],
    specs: [
      { label: "Genre", value: "Action / Open World" },
      { label: "Format", value: "Blu-ray Disc (PS5)" },
      { label: "Players", value: "1 + Online" },
    ],
    compatibility: ["PlayStation 5", "PlayStation 5 Slim", "PlayStation 5 Pro"],
    featured: true,
    bestSeller: true,
    onDeal: true,
    dealEndsAt: new Date(Date.now() + 1000 * 60 * 60 * 30).toISOString(),
    createdAt: "2026-07-01T10:00:00Z",
  },
  {
    id: "prod-26",
    handle: "wwe-2k26-ps5",
    title: "WWE 2K26 — PS5 Disc",
    brand: "2K",
    description:
      "Top wrestling seller in Pakistan. Updated roster, MyRISE, and local multiplayer — sealed original PS5 disc.",
    category: "ps5-games",
    categoryPath: ["games", "ps5-games", "new-releases"],
    platform: ["PlayStation 5"],
    tags: ["game", "ps5-cd", "top-pakistan", "wrestling"],
    condition: "new",
    rating: 4.5,
    reviewCount: 410,
    images: [img("photo-1511512578047-dfb367046420", "WWE 2K26 PS5 disc")],
    variants: [
      {
        id: "var-26",
        title: "Physical Disc",
        sku: "PTPK-GAME-WWE2K26-PS5",
        price: pkr(15200),
        available: true,
        quantityAvailable: 95,
      },
    ],
    specs: [
      { label: "Genre", value: "Sports / Fighting" },
      { label: "Format", value: "Blu-ray Disc (PS5)" },
      { label: "Players", value: "1–4" },
    ],
    compatibility: ["PlayStation 5", "PlayStation 5 Slim", "PlayStation 5 Pro"],
    bestSeller: true,
    newArrival: true,
    featured: true,
    createdAt: "2026-03-14T10:00:00Z",
  },
  {
    id: "prod-27",
    handle: "spiderman-2-ps5",
    title: "Marvel's Spider-Man 2 — PS5 Disc",
    brand: "Sony",
    description:
      "One of Pakistan’s top exclusive PS5 disc sales. Swing through New York as Peter and Miles — original sealed CD.",
    category: "ps5-games",
    categoryPath: ["games", "ps5-games", "best-sellers"],
    platform: ["PlayStation 5"],
    tags: ["game", "ps5-cd", "top-pakistan", "exclusive"],
    condition: "new",
    rating: 4.9,
    reviewCount: 1850,
    images: [img("photo-1550745165-9bc0b252726f", "Spider-Man 2 PS5 disc")],
    variants: [
      {
        id: "var-27",
        title: "Physical Disc",
        sku: "PTPK-GAME-SM2-PS5-NEW",
        price: pkr(12999),
        compareAtPrice: pkr(14999),
        available: true,
        quantityAvailable: 140,
      },
    ],
    specs: [
      { label: "Genre", value: "Action-Adventure" },
      { label: "Format", value: "Blu-ray Disc (PS5)" },
      { label: "Players", value: "1" },
    ],
    compatibility: ["PlayStation 5", "PlayStation 5 Slim", "PlayStation 5 Pro"],
    bestSeller: true,
    featured: true,
    onDeal: true,
    dealEndsAt: new Date(Date.now() + 1000 * 60 * 60 * 22).toISOString(),
    createdAt: "2026-06-15T10:00:00Z",
  },
  {
    id: "prod-28",
    handle: "god-of-war-ragnarok-ps5",
    title: "God of War Ragnarök — PS5 Disc",
    brand: "Sony",
    description:
      "Kratos & Atreus epic — consistently among the most ordered PS5 exclusives in Lahore, Karachi, and Islamabad shops.",
    category: "ps5-games",
    categoryPath: ["games", "ps5-games", "best-sellers"],
    platform: ["PlayStation 5"],
    tags: ["game", "ps5-cd", "top-pakistan", "exclusive"],
    condition: "new",
    rating: 4.9,
    reviewCount: 2100,
    images: [img("photo-1552820728-8b83bb6b773f", "God of War Ragnarok PS5")],
    variants: [
      {
        id: "var-28",
        title: "Physical Disc",
        sku: "PTPK-GAME-GOWR-PS5",
        price: pkr(9999),
        compareAtPrice: pkr(11999),
        available: true,
        quantityAvailable: 110,
      },
    ],
    specs: [
      { label: "Genre", value: "Action-Adventure" },
      { label: "Format", value: "Blu-ray Disc (PS5)" },
      { label: "Players", value: "1" },
    ],
    compatibility: ["PlayStation 5", "PlayStation 5 Slim", "PlayStation 5 Pro"],
    bestSeller: true,
    featured: true,
    createdAt: "2026-05-20T10:00:00Z",
  },
  {
    id: "prod-29",
    handle: "tekken-8-ps5",
    title: "TEKKEN 8 — PS5 Disc",
    brand: "Bandai Namco",
    description:
      "Pakistan’s #1 fighting-game disc demand. Arcade-perfect combat and online ranked — sealed PS5 CD.",
    category: "ps5-games",
    categoryPath: ["games", "ps5-games", "best-sellers"],
    platform: ["PlayStation 5"],
    tags: ["game", "ps5-cd", "top-pakistan", "fighting"],
    condition: "new",
    rating: 4.8,
    reviewCount: 980,
    images: [img("photo-1511512578047-dfb367046420", "Tekken 8 PS5 disc")],
    variants: [
      {
        id: "var-29",
        title: "Physical Disc",
        sku: "PTPK-GAME-TK8-PS5",
        price: pkr(10999),
        available: true,
        quantityAvailable: 130,
      },
    ],
    specs: [
      { label: "Genre", value: "Fighting" },
      { label: "Format", value: "Blu-ray Disc (PS5)" },
      { label: "Players", value: "1–2" },
    ],
    compatibility: ["PlayStation 5", "PlayStation 5 Slim", "PlayStation 5 Pro"],
    bestSeller: true,
    featured: true,
    createdAt: "2026-04-12T10:00:00Z",
  },
  {
    id: "prod-30",
    handle: "mortal-kombat-1-ps5",
    title: "Mortal Kombat 1 — PS5 Disc",
    brand: "Warner Bros",
    description:
      "High-demand fighter across Pakistani game markets. Original PS5 physical disc with story and online play.",
    category: "ps5-games",
    categoryPath: ["games", "ps5-games"],
    platform: ["PlayStation 5"],
    tags: ["game", "ps5-cd", "top-pakistan", "fighting"],
    condition: "new",
    rating: 4.6,
    reviewCount: 720,
    images: [img("photo-1493711662062-fa541adb3fc8", "Mortal Kombat 1 PS5")],
    variants: [
      {
        id: "var-30",
        title: "Physical Disc",
        sku: "PTPK-GAME-MK1-PS5",
        price: pkr(8950),
        compareAtPrice: pkr(9999),
        available: true,
        quantityAvailable: 100,
      },
    ],
    specs: [
      { label: "Genre", value: "Fighting" },
      { label: "Format", value: "Blu-ray Disc (PS5)" },
      { label: "Players", value: "1–2" },
    ],
    compatibility: ["PlayStation 5", "PlayStation 5 Slim", "PlayStation 5 Pro"],
    bestSeller: true,
    onDeal: true,
    dealEndsAt: new Date(Date.now() + 1000 * 60 * 60 * 16).toISOString(),
    createdAt: "2026-03-22T10:00:00Z",
  },
  {
    id: "prod-31",
    handle: "call-of-duty-black-ops-6-ps5",
    title: "Call of Duty: Black Ops 6 — PS5 Disc",
    brand: "Activision",
    description:
      "FPS staple in Pakistan — campaign, multiplayer, and Zombies on original PS5 disc for easy trade-in value.",
    category: "ps5-games",
    categoryPath: ["games", "ps5-games", "best-sellers"],
    platform: ["PlayStation 5"],
    tags: ["game", "ps5-cd", "top-pakistan", "fps"],
    condition: "new",
    rating: 4.4,
    reviewCount: 1500,
    images: [img("photo-1542751371-adc38448a05e", "Call of Duty PS5 disc")],
    variants: [
      {
        id: "var-31",
        title: "Physical Disc",
        sku: "PTPK-GAME-BO6-PS5",
        price: pkr(13999),
        available: true,
        quantityAvailable: 85,
      },
    ],
    specs: [
      { label: "Genre", value: "FPS" },
      { label: "Format", value: "Blu-ray Disc (PS5)" },
      { label: "Players", value: "1 + Online" },
    ],
    compatibility: ["PlayStation 5", "PlayStation 5 Slim", "PlayStation 5 Pro"],
    bestSeller: true,
    featured: true,
    createdAt: "2026-02-10T10:00:00Z",
  },
  {
    id: "prod-32",
    handle: "last-of-us-part-ii-remastered-ps5",
    title: "The Last of Us Part II Remastered — PS5 Disc",
    brand: "Sony",
    description:
      "Story-driven exclusive that stays in Pakistan’s top PS5 CD charts. Remastered for DualSense and 4K.",
    category: "ps5-games",
    categoryPath: ["games", "ps5-games"],
    platform: ["PlayStation 5"],
    tags: ["game", "ps5-cd", "top-pakistan", "exclusive"],
    condition: "new",
    rating: 4.8,
    reviewCount: 1340,
    images: [img("photo-1550745165-9bc0b252726f", "Last of Us Part II Remastered")],
    variants: [
      {
        id: "var-32",
        title: "Physical Disc",
        sku: "PTPK-GAME-TLOU2R-PS5",
        price: pkr(11999),
        available: true,
        quantityAvailable: 90,
      },
    ],
    specs: [
      { label: "Genre", value: "Action-Adventure" },
      { label: "Format", value: "Blu-ray Disc (PS5)" },
      { label: "Players", value: "1" },
    ],
    compatibility: ["PlayStation 5", "PlayStation 5 Slim", "PlayStation 5 Pro"],
    bestSeller: true,
    createdAt: "2026-01-28T10:00:00Z",
  },
  {
    id: "prod-33",
    handle: "ghost-of-tsushima-directors-cut-ps5",
    title: "Ghost of Tsushima Director's Cut — PS5 Disc",
    brand: "Sony",
    description:
      "Samurai open-world favourite among Pakistani PS5 disc buyers. Includes Iki Island expansion on disc edition.",
    category: "ps5-games",
    categoryPath: ["games", "ps5-games"],
    platform: ["PlayStation 5"],
    tags: ["game", "ps5-cd", "top-pakistan", "exclusive"],
    condition: "new",
    rating: 4.9,
    reviewCount: 1100,
    images: [img("photo-1606144042614-b2417e99c4e3", "Ghost of Tsushima PS5")],
    variants: [
      {
        id: "var-33",
        title: "Physical Disc",
        sku: "PTPK-GAME-GOTDC-PS5",
        price: pkr(9999),
        compareAtPrice: pkr(12499),
        available: true,
        quantityAvailable: 75,
      },
    ],
    specs: [
      { label: "Genre", value: "Action-Adventure" },
      { label: "Format", value: "Blu-ray Disc (PS5)" },
      { label: "Players", value: "1 + Legends Online" },
    ],
    compatibility: ["PlayStation 5", "PlayStation 5 Slim", "PlayStation 5 Pro"],
    bestSeller: true,
    onDeal: true,
    dealEndsAt: new Date(Date.now() + 1000 * 60 * 60 * 50).toISOString(),
    createdAt: "2026-04-01T10:00:00Z",
  },
  {
    id: "prod-34",
    handle: "nba-2k26-ps5",
    title: "NBA 2K26 — PS5 Disc",
    brand: "2K",
    description:
      "Basketball sim that ranks high in Pakistan’s sports-game disc orders every season. Sealed PS5 CD.",
    category: "ps5-games",
    categoryPath: ["games", "ps5-games", "new-releases"],
    platform: ["PlayStation 5"],
    tags: ["game", "ps5-cd", "top-pakistan", "sports"],
    condition: "new",
    rating: 4.3,
    reviewCount: 560,
    images: [img("photo-1574629810360-7efbbe195018", "NBA 2K26 PS5 disc")],
    variants: [
      {
        id: "var-34",
        title: "Physical Disc",
        sku: "PTPK-GAME-NBA2K26-PS5",
        price: pkr(14999),
        available: true,
        quantityAvailable: 70,
      },
    ],
    specs: [
      { label: "Genre", value: "Sports" },
      { label: "Format", value: "Blu-ray Disc (PS5)" },
      { label: "Players", value: "1–4" },
    ],
    compatibility: ["PlayStation 5", "PlayStation 5 Slim", "PlayStation 5 Pro"],
    bestSeller: true,
    newArrival: true,
    createdAt: "2026-07-10T10:00:00Z",
  },
  {
    id: "prod-35",
    handle: "assassins-creed-shadows-ps5",
    title: "Assassin's Creed Shadows — PS5 Disc",
    brand: "Ubisoft",
    description:
      "Feudal Japan open-world hit with strong PS5 disc demand in Pakistani retailers — original physical edition.",
    category: "ps5-games",
    categoryPath: ["games", "ps5-games", "new-releases"],
    platform: ["PlayStation 5"],
    tags: ["game", "ps5-cd", "top-pakistan", "adventure"],
    condition: "new",
    rating: 4.5,
    reviewCount: 640,
    images: [img("photo-1552820728-8b83bb6b773f", "Assassins Creed Shadows PS5")],
    variants: [
      {
        id: "var-35",
        title: "Physical Disc",
        sku: "PTPK-GAME-ACS-PS5",
        price: pkr(15999),
        available: true,
        quantityAvailable: 60,
      },
    ],
    specs: [
      { label: "Genre", value: "Action-Adventure" },
      { label: "Format", value: "Blu-ray Disc (PS5)" },
      { label: "Players", value: "1" },
    ],
    compatibility: ["PlayStation 5", "PlayStation 5 Slim", "PlayStation 5 Pro"],
    bestSeller: true,
    newArrival: true,
    featured: true,
    createdAt: "2026-07-05T10:00:00Z",
  },
  {
    id: "prod-36",
    handle: "red-dead-redemption-2-ps5",
    title: "Red Dead Redemption 2 — PS5 Disc",
    brand: "Rockstar",
    description:
      "Western epic still selling hard as a PS5-compatible disc in Pakistan’s pre-owned and new CD markets.",
    category: "ps5-games",
    categoryPath: ["games", "ps5-games", "best-sellers"],
    platform: ["PlayStation 5", "PlayStation 4"],
    tags: ["game", "ps5-cd", "top-pakistan", "open-world"],
    condition: "new",
    rating: 4.9,
    reviewCount: 2400,
    images: [img("photo-1493711662062-fa541adb3fc8", "Red Dead Redemption 2 disc")],
    variants: [
      {
        id: "var-36",
        title: "Physical Disc",
        sku: "PTPK-GAME-RDR2-PS5",
        price: pkr(7499),
        compareAtPrice: pkr(8999),
        available: true,
        quantityAvailable: 160,
      },
    ],
    specs: [
      { label: "Genre", value: "Action / Open World" },
      { label: "Format", value: "Blu-ray Disc" },
      { label: "Players", value: "1 + Online" },
    ],
    compatibility: ["PlayStation 5", "PlayStation 5 Slim", "PlayStation 5 Pro", "PlayStation 4"],
    bestSeller: true,
    onDeal: true,
    dealEndsAt: new Date(Date.now() + 1000 * 60 * 60 * 28).toISOString(),
    createdAt: "2026-02-18T10:00:00Z",
  },
];

export const DEMO_NEWS: NewsArticle[] = [];

export const DEMO_REVIEWS = [
  {
    id: "rev-1",
    author: "Ayesha K.",
    rating: 5,
    title: "Genuine and fast delivery",
    body: "Controller arrived sealed. DualSense haptics feel incredible in Astro Bot.",
    createdAt: "2026-07-10T12:00:00Z",
  },
  {
    id: "rev-2",
    author: "Hassan R.",
    rating: 4,
    title: "Solid build",
    body: "Great price for Pakistan market. Packaging was secure.",
    createdAt: "2026-07-02T12:00:00Z",
  },
  {
    id: "rev-3",
    author: "Sara M.",
    rating: 5,
    title: "Will buy again",
    body: "ToyCompany checkout was smooth and JazzCash payment worked instantly.",
    createdAt: "2026-06-28T12:00:00Z",
  },
];
